master:
  ports:
    - "4505:4505"
    - "4506:4506"
    - "2222:2222"
    - "2223:2223"
    - "2224:2224"
    - "10389:10389"
  image: "shadowhosting/master"
  dns: "172.17.0.1"
  volumes:
    - "/root/.ssh/id_ed25519.pub:/root/.ssh/authorized_keys"
    - "/vagrant/controllerContainer/master/config/etc/pki/tls/certs/localhost.key:/etc/pki/tls/certs/localhost.key"
    - "/vagrant/controllerContainer/master/config/etc/ssh/sshd_config:/etc/ssh/sshd_config"
    - "/vagrant/controllerContainer/master/config/etc/supervisord.conf:/etc/supervisord.conf"
    - "/vagrant/controllerContainer/master/opt:/opt"
    - "/vagrant/controllerApp/:/opt/controllerApp"
    - "/vagrant/controllerContainer/master/config/etc/openvpn:/etc/openvpn"
    - "/vagrant/controllerContainer/master/config/etc/pki/tls/certs/localhost.crt:/etc/pki/tls/certs/localhost.crt"
    - "/vagrant/controllerContainer/master/config/etc/salt:/etc/salt"
    - "/vagrant/controllerContainer/master/log/supervisor:/var/log/supervisor"
    - "/vagrant/controllerContainer/master/srv:/srv"

servicerouter:
  ports:
    - "53:53"
    - "53:53/udp"
    - "3003:3003"
  image: "tonistiigi/dnsdock"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

