#!/bin/bash
ARGS='"ARGS":["SSHPORT", "TESTVAR"]'     #this decleration MUST be on the 2nd line, and in this format
CTYPE( )
{
 echo application/json
}

STRATEGY( )
{
  echo async
}

RUN( )
{
 for num in $(seq 1 100)
 do
   prox=$(uptime | cut -d ':' -f 5 | cut -d ',' -f 1 | sed 's/ //g')
   output=$($JQPath -n -c --arg d "$num" --arg p "$prox" '{x:$d,y:$p}')
   echo $output
   CALLBACK $output
   sleep .4
 done
   
}
