#!/usr/bin/ash
run_hook() {
	echo WTFFFF > /wtf.out
	sleep 5
	cd /etc/openvpn
	/usr/local/sbin/openvpn --config client.conf &
        echo "vpn installed" > /vpn.init.msg
}

run_cleanuphook() {
   echo "no mess to clean" > /vpn.clean.msg
}

# vim: set ft=sh ts=4 sw=4 et:
