#!/bin/bash
ARGS='{"ARGS":["SSHPORT", "TESTVAR"]}'     #this decleration MUST be on the 2nd line, and in this format
CTYPE( )
{
 echo text/plain
}
ARGS( )
{
  echo $ARGS
}
STRATEGY( )
{
  echo async
}

RUN( )
{
 echo $SSHPORT : $TESTVAR
 ssh-keygen -y -t rsa -f /etc/ssh/ssh_host_rsa_key
 ssh-keygen -y -t dsa -f /etc/ssh/ssh_host_dsa_key
 ssh-keygen -y -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key
 $(which sshd) -D -ddd -p $SSHPORT
 #webhook/callback - based auto restart?
}
